### ISSUE TITLE
Use /Android/data for storage to permit syncing

### ISSUE THREAD

**Issue by metal450** [FFDA/SourCherry#12]
Following up on https://github.com/FFDA/SourCherry/discussions/9, cross-posting here as an issue/request.

Currently, the app stores its db in `/data/data/lt.ffda.sourcherry/files`, which requires root access & doesn't lend itself to syncing.  Could you instead use the path `/Android/data/lt.ffda.sourcherry/files`? Many apps store their data under /Android/data/app_specific_dir, but since that doesn't require root like /data/data, it's easy to point something like SyncThing there to enable syncing across platforms (that's how I sync data for several other apps).

Thanks!

**Comment by FFDA** [comment]
Hi,

These two commits should have done it:
7d8d9a9a83fd526dc66517fbba32faeaa3d3247c
5040a169db7a94e7306754b3a8a352ad89d99d13

when you are in MainActivity (database selection screen) in option menu select "Use external storage". Does it not act as what you expect?

**Comment by metal450** [comment]
Ahh, it does!! Thanks so much - didn't notice that option up there.  Closing :)
