### ISSUE TITLE
Upload to Google Play

### ISSUE THREAD

**Issue by predator8bit** [FFDA/SourCherry#14]
I think it would be a good idea to have the app on the Play store or whatever it's name is nowadays. It is a bit inconvenient having to install f-droid onto other people's phones when I want to share cherrytree databases.

**Comment by FFDA** [comment]
Its' already in the Play Store. You can find link on [repo page](https://github.com/FFDA/SourCherry#installation--download) or by searching the Play Store.
I didn't put the app on the F-Droid. I know that it is possible to install it thought F-Droid, but you have to add additional repo to the app.

**Comment by predator8bit** [comment]
Sorrymy bad, it just didn't show up on my searches, but must be something wrong with Aurora Store.
