### ISSUE TITLE
Won't open formated text in Rich Text Node

### ISSUE THREAD

**Issue by erwinfamilist** [FFDA/SourCherry#2]
Hy,
I have a 567 KB database, exported in XML format and opened in SourCherry (Alpha-2). My database is very basic, I use Rich Text Nodes, some with formatting (Bold, Italic, Underline, Background Color, Font Colour), some without.
When I open a node without formatting in SourCherry, it opens the node just fine, BUT when I open a node with whatsoever formatting the app flashes for a half second when it shows the start screen( Create, Select Database, Open Buttons) and than it opens automatically the database as if I just opened it.
A node had some formatting, that was not visible and won't display it (I presume a Bold formatting on a "space", SourCherry won't display it only after I removed formatting of the entire text of the node in Cherrytree, exported it to my Phone and than when I opened the node it displayed it)

Thank you in advance,
Best regards,
Erwin

PS. I am very happy for finding your app and VERY GRATEFUL for your work! God bless you!

**Comment by FFDA** [comment]
Hi, app definitely crashes for some reason if it reloads to main activity (the one that lets you to select a database). 

> and than it opens automatically the database as if I just opened it.

What do you mean by this? Does the app manages to open the database on the second try?

Please, try a bit newer version than alpha-2, that most likely will be a beta version. It supports most (if not all) of rich-text formatting. [Download](https://github.com/FFDA/ffda.github.storage/raw/main/SourCherry-releases/SourCherry-alpha-2-nightDebug.apk)
![image](https://user-images.githubusercontent.com/8406967/174469295-81070295-4012-4a26-998b-ef3643c39058.png)

If that apk still crashes please tell me more about your phone (android version) and provide a sample of the database (you can make a sample one just for me) or[ download one of these](https://github.com/FFDA/ffda.github.storage/tree/main/test_databases) and modify it in a way that you think might have caused the crash.

BTW, from alpha-2 you can use SQL based databases with the app, so while I appreciate that you trying out XML databases you do not have to use them any longer. However, they do have feature parity.

**Comment by erwinfamilist** [comment]
Hi, 
I installed the nightDebug and exported the Sql database.
Same bug appears.

take a look here:
https://ugetube.com/watch/7HKUHSt1xf7itE2

I also tried your sample databases in SQL and they worked just fine, displayed every type of formatting.
I opened even in Cherrytree and exported it like my database and it worked in SourCherry.

Do you have any idea what could be the problem?

I send you my database, maybe you can figure it out.

Thank you very much
[cherrytreedb t2 sql.ctb.zip](https://github.com/FFDA/SourCherry/files/8934979/cherrytreedb.t2.sql.ctb.zip)
.

**Comment by FFDA** [comment]
Thank you for providing a sample. It made it really easy to find the cause of the crash. I think I fixed it, but I would like you to test it on your phone and confirm it for me. 

You can [download it form here](https://github.com/FFDA/ffda.github.storage/raw/main/SourCherry-releases/SourCherry-alpha-2-colorCodeDebug.apk).

**Comment by erwinfamilist** [comment]
Thank you, it works now. God bless you!
