### ISSUE TITLE
Adding fonts?

### ISSUE THREAD

**Issue by GoldenGlimpse** [FFDA/SourCherry#20]
Hi,
Is it possible to add fonts? 
I make rhythm notations and i need the characters to be spaced evenly so the lines match up in blocks.

for example:
D___Tk__D___T_T___
D_tkT_k_D_tkT_T_tk

As you can see, the lines don't match up, yet they both have 18 characters. 
How can i fix this please. Thanks.

**Comment by GoldenGlimpse** [comment]
Thank you for your response. Unfortunately i don't know much about fonts. All i know is sometimes the lines match up, and sometimes they don't. There is probably many fonts that do so. 

This is the same line example on desktop, 18 characters per line:
![rhy example font](https://github.com/user-attachments/assets/bd1554e3-f202-4bbc-a69f-f9870bd37fae)

Imported into SourCherry it looks like this: (changing font settings doesn't make the lines line up)
![Screenshot2](https://github.com/user-attachments/assets/7dc48585-e9ef-48fe-a123-d663e544c8fe)

Small letters are not as wide as capital letters.

both 8 characters:
T_T_T_T_  
t_t_t_t_

Settings in CherryTree:
![cherry font](https://github.com/user-attachments/assets/d76fabf6-8244-4f47-bd0c-890602143bf3)

**Comment by FFDA** [comment]
So, you're using monospace fonts. I'll try to include one in the next release, though I’m not sure when that will be.

Oh, and I found out that there’s an option to make only the selected text monospaced in CherryTree as well.
![image](https://github.com/user-attachments/assets/01f9b3da-1ff8-4ba2-8755-6b46e8e6d4d4)

**Comment by GoldenGlimpse** [comment]
Wonderful, thank you very much. Looking forward to the next release.
