### ISSUE TITLE
Unable to open Cherry Tree document

### ISSUE THREAD

**Issue by zstankowicz** [FFDA/SourCherry#3]
Hey,

I know this is early alpha, but I just tried to open my CherryTree file (stored on google drive) and all I get is "Doesn't look like a CherryTree database". 
I've tried both the ctd (XML) and the ctb (sqlite) but with the same result.

Any suggestions on what I can do to check why it doesn't get recognized?
File is around 500kB, no flashy things. Plenty of text, some basic formatting.

**Comment by zstankowicz** [comment]
Thank you very much for the reply and the new apk. 
Now it works like a charm.
Feel free to close the ticket.

I hope you'll have the persistence to continue developing the tool. There's a big gap and big demand for it. Maybe Kickstarter/Patreon?

**Comment by FFDA** [comment]
Thank you for the confirmation.

> I hope you'll have the persistence to continue developing the tool. There's a big gap and big demand for it. Maybe Kickstarter/Patreon?

No, there is no need for that. This project is just for learning purposes. I don't event plan to put any adds in it and I don't want to make any promises or feel obliged to do something I might not be able to.
